# Generated by Django 5.2.8 on 2025-12-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_board_owner_alter_ticket_board_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='details',
            new_name='description',
        ),
        migrations.AddField(
            model_name='ticket',
            name='title',
            field=models.CharField(default='NEW', max_length=175),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('INPROGRESS', 'In progress'), ('DONE', 'Done')], default='NEW', max_length=10),
        ),
    ]
