# Generated by Django 5.2.8 on 2026-03-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_board_description_alter_ticket_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ACTIVE', 'Active'), ('DONE', 'Done')], default='NEW', max_length=10),
        ),
    ]
