# Generated by Django 5.2.8 on 2026-03-14 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_ticket_statuschangedat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['statusChangedAt']},
        ),
    ]
