# Generated by Django 5.2.8 on 2026-03-14 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_ticket_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='description',
        ),
    ]
