# Generated by Django 5.2.8 on 2026-03-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_board_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
