# Generated by Django 5.2.8 on 2026-01-24 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_name_board_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='details',
            new_name='description',
        ),
    ]
